In [40]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data_source = '../data/'

In [4]:
df = pd.read_csv(data_source + 'adult.data.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
df["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

In [8]:
df[df["sex"] == "Female"]["age"].mean()

np.float64(36.85823043357163)

In [ ]:
df['native-country' ].value_counts(normalize=True)

native-country
United-States                 0.895857
Mexico                        0.019748
?                             0.017905
Philippines                   0.006081
Germany                       0.004207
Canada                        0.003716
Puerto-Rico                   0.003501
El-Salvador                   0.003255
India                         0.003071
Cuba                          0.002918
England                       0.002764
Jamaica                       0.002488
South                         0.002457
China                         0.002303
Italy                         0.002242
Dominican-Republic            0.002150
Vietnam                       0.002058
Guatemala                     0.001966
Japan                         0.001904
Poland                        0.001843
Columbia                      0.001812
Taiwan                        0.001566
Haiti                         0.001351
Iran                          0.001321
Portugal                      0.001136
Nicaragua                     0.001044
Peru                          0.000952
France                        0.000891
Greece                        0.000891
Ecuador                       0.000860
Ireland                       0.000737
Hong                          0.000614
Cambodia                      0.000584
Trinadad&Tobago               0.000584
Thailand                      0.000553
Laos                          0.000553
Yugoslavia                    0.000491
Outlying-US(Guam-USVI-etc)    0.000430
Honduras                      0.000399
Hungary                       0.000399
Scotland                      0.000369
Holand-Netherlands            0.000031
Name: proportion, dtype: float64

In [32]:
df[(df['sex'] == 'Male') & (df['salary'] == '>50K')]['age'].describe()

count    6662.000000
mean       44.625788
std        10.485469
min        19.000000
25%        37.000000
50%        44.000000
75%        51.000000
max        90.000000
Name: age, dtype: float64

In [33]:
df[(df['sex'] == 'Male') & (df['salary'] == '<=50K')]['age'].describe()

count    15128.000000
mean        37.147012
std         13.856113
min         17.000000
25%         26.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64

In [43]:
df[df['education'].isin(['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters' ,'Doctorate'])]
df[df['salary'] == '>50K']

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [42]:
pd.crosstab(
    df['education'].isin(['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters' ,'Doctorate']),
    df['salary'] == '>50K', 
    margins=True)

salary     False  True    All
education
False      18739  3306  22045
True        5981  4535  10516
All        24720  7841  32561

In [46]:
df[df['race'] == 'Amer-Indian-Eskimo']['age'].max()

np.int64(82)

In [52]:
pd.crosstab(
    df['salary'] == '>50K',
    df['marital-status'].isin(['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']),
    margins=True,
)

marital-status  False   True    All
salary
False           16039   8681  24720
True             1105   6736   7841
All             17144  15417  32561

In [62]:
df['hours-per-week'].sort_values(ascending=False).value_counts()

hours-per-week
40    15217
50     2819
45     1824
60     1475
35     1297
      ...
94        1
92        1
87        1
82        1
74        1
Name: count, Length: 94, dtype: int64

In [88]:
df['earn a lot'] = (df['salary'] == '>50K')
ans = df.groupby(['native-country', 'earn a lot'])['hours-per-week'].agg(['mean'])
ans.loc['Japan']

                 mean
earn a lot
False       41.000000
True        47.958333